import SvgBase from './component/SvgBase';
import IconBase from './component/IconBase';
import AccountBookDefault, { AccountBook } from './icon/AccountBook.ts';
import AlertDefault, { Alert } from './icon/Alert.ts';
import AlipayCircleDefault, { AlipayCircle } from './icon/AlipayCircle.ts';
import AlipaySquareDefault, { AlipaySquare } from './icon/AlipaySquare.ts';
import AliwangwangDefault, { Aliwangwang } from './icon/Aliwangwang.ts';
import AmazonCircleDefault, { AmazonCircle } from './icon/AmazonCircle.ts';
import AmazonSquareDefault, { AmazonSquare } from './icon/AmazonSquare.ts';
import AndroidDefault, { Android } from './icon/Android.ts';
import ApiDefault, { Api } from './icon/Api.ts';
import AppleDefault, { Apple } from './icon/Apple.ts';
import AppstoreDefault, { Appstore } from './icon/Appstore.ts';
import AudioDefault, { Audio } from './icon/Audio.ts';
import BackwardDefault, { Backward } from './icon/Backward.ts';
import BankDefault, { Bank } from './icon/Bank.ts';
import BehanceCircleDefault, { BehanceCircle } from './icon/BehanceCircle.ts';
import BehanceSquareDefault, { BehanceSquare } from './icon/BehanceSquare.ts';
import BellDefault, { Bell } from './icon/Bell.ts';
import BookDefault, { Book } from './icon/Book.ts';
import BoxPlotDefault, { BoxPlot } from './icon/BoxPlot.ts';
import BugDefault, { Bug } from './icon/Bug.ts';
import BuildDefault, { Build } from './icon/Build.ts';
import BulbDefault, { Bulb } from './icon/Bulb.ts';
import CalculatorDefault, { Calculator } from './icon/Calculator.ts';
import CalendarDefault, { Calendar } from './icon/Calendar.ts';
import CameraDefault, { Camera } from './icon/Camera.ts';
import CarDefault, { Car } from './icon/Car.ts';
import CaretDownDefault, { CaretDown } from './icon/CaretDown.ts';
import CaretLeftDefault, { CaretLeft } from './icon/CaretLeft.ts';
import CaretRightDefault, { CaretRight } from './icon/CaretRight.ts';
import CaretUpDefault, { CaretUp } from './icon/CaretUp.ts';
import CarryOutDefault, { CarryOut } from './icon/CarryOut.ts';
import CheckCircleDefault, { CheckCircle } from './icon/CheckCircle.ts';
import CheckSquareDefault, { CheckSquare } from './icon/CheckSquare.ts';
import ChromeDefault, { Chrome } from './icon/Chrome.ts';
import CiCircleDefault, { CiCircle } from './icon/CiCircle.ts';
import ClockCircleDefault, { ClockCircle } from './icon/ClockCircle.ts';
import CloseCircleDefault, { CloseCircle } from './icon/CloseCircle.ts';
import CloseSquareDefault, { CloseSquare } from './icon/CloseSquare.ts';
import CloudDefault, { Cloud } from './icon/Cloud.ts';
import CodeSandboxCircleDefault, { CodeSandboxCircle } from './icon/CodeSandboxCircle.ts';
import CodeSandboxSquareDefault, { CodeSandboxSquare } from './icon/CodeSandboxSquare.ts';
import CodeDefault, { Code } from './icon/Code.ts';
import CodepenCircleDefault, { CodepenCircle } from './icon/CodepenCircle.ts';
import CodepenSquareDefault, { CodepenSquare } from './icon/CodepenSquare.ts';
import CompassDefault, { Compass } from './icon/Compass.ts';
import ContactsDefault, { Contacts } from './icon/Contacts.ts';
import ContainerDefault, { Container } from './icon/Container.ts';
import ControlDefault, { Control } from './icon/Control.ts';
import CopyDefault, { Copy } from './icon/Copy.ts';
import CopyrightCircleDefault, { CopyrightCircle } from './icon/CopyrightCircle.ts';
import CreditCardDefault, { CreditCard } from './icon/CreditCard.ts';
import CrownDefault, { Crown } from './icon/Crown.ts';
import CustomerServiceDefault, { CustomerService } from './icon/CustomerService.ts';
import DashboardDefault, { Dashboard } from './icon/Dashboard.ts';
import DatabaseDefault, { Database } from './icon/Database.ts';
import DeleteDefault, { Delete } from './icon/Delete.ts';
import DiffDefault, { Diff } from './icon/Diff.ts';
import DingtalkCircleDefault, { DingtalkCircle } from './icon/DingtalkCircle.ts';
import DingtalkSquareDefault, { DingtalkSquare } from './icon/DingtalkSquare.ts';
import DislikeDefault, { Dislike } from './icon/Dislike.ts';
import DollarCircleDefault, { DollarCircle } from './icon/DollarCircle.ts';
import DownCircleDefault, { DownCircle } from './icon/DownCircle.ts';
import DownSquareDefault, { DownSquare } from './icon/DownSquare.ts';
import DribbbleCircleDefault, { DribbbleCircle } from './icon/DribbbleCircle.ts';
import DribbbleSquareDefault, { DribbbleSquare } from './icon/DribbbleSquare.ts';
import DropboxCircleDefault, { DropboxCircle } from './icon/DropboxCircle.ts';
import DropboxSquareDefault, { DropboxSquare } from './icon/DropboxSquare.ts';
import EditDefault, { Edit } from './icon/Edit.ts';
import EnvironmentDefault, { Environment } from './icon/Environment.ts';
import EuroCircleDefault, { EuroCircle } from './icon/EuroCircle.ts';
import ExclamationCircleDefault, { ExclamationCircle } from './icon/ExclamationCircle.ts';
import ExperimentDefault, { Experiment } from './icon/Experiment.ts';
import EyeInvisibleDefault, { EyeInvisible } from './icon/EyeInvisible.ts';
import EyeDefault, { Eye } from './icon/Eye.ts';
import FacebookDefault, { Facebook } from './icon/Facebook.ts';
import FastBackwardDefault, { FastBackward } from './icon/FastBackward.ts';
import FastForwardDefault, { FastForward } from './icon/FastForward.ts';
import FileAddDefault, { FileAdd } from './icon/FileAdd.ts';
import FileExcelDefault, { FileExcel } from './icon/FileExcel.ts';
import FileExclamationDefault, { FileExclamation } from './icon/FileExclamation.ts';
import FileImageDefault, { FileImage } from './icon/FileImage.ts';
import FileMarkdownDefault, { FileMarkdown } from './icon/FileMarkdown.ts';
import FilePdfDefault, { FilePdf } from './icon/FilePdf.ts';
import FilePptDefault, { FilePpt } from './icon/FilePpt.ts';
import FileTextDefault, { FileText } from './icon/FileText.ts';
import FileUnknownDefault, { FileUnknown } from './icon/FileUnknown.ts';
import FileWordDefault, { FileWord } from './icon/FileWord.ts';
import FileZipDefault, { FileZip } from './icon/FileZip.ts';
import FileDefault, { File } from './icon/File.ts';
import FilterDefault, { Filter } from './icon/Filter.ts';
import FireDefault, { Fire } from './icon/Fire.ts';
import FlagDefault, { Flag } from './icon/Flag.ts';
import FolderAddDefault, { FolderAdd } from './icon/FolderAdd.ts';
import FolderOpenDefault, { FolderOpen } from './icon/FolderOpen.ts';
import FolderDefault, { Folder } from './icon/Folder.ts';
import FormatPainterDefault, { FormatPainter } from './icon/FormatPainter.ts';
import ForwardDefault, { Forward } from './icon/Forward.ts';
import FrownDefault, { Frown } from './icon/Frown.ts';
import FundDefault, { Fund } from './icon/Fund.ts';
import FunnelPlotDefault, { FunnelPlot } from './icon/FunnelPlot.ts';
import GiftDefault, { Gift } from './icon/Gift.ts';
import GithubDefault, { Github } from './icon/Github.ts';
import GitlabDefault, { Gitlab } from './icon/Gitlab.ts';
import GoldDefault, { Gold } from './icon/Gold.ts';
import GoldenDefault, { Golden } from './icon/Golden.ts';
import GoogleCircleDefault, { GoogleCircle } from './icon/GoogleCircle.ts';
import GooglePlusCircleDefault, { GooglePlusCircle } from './icon/GooglePlusCircle.ts';
import GooglePlusSquareDefault, { GooglePlusSquare } from './icon/GooglePlusSquare.ts';
import GoogleSquareDefault, { GoogleSquare } from './icon/GoogleSquare.ts';
import HddDefault, { Hdd } from './icon/Hdd.ts';
import HeartDefault, { Heart } from './icon/Heart.ts';
import HighlightDefault, { Highlight } from './icon/Highlight.ts';
import HomeDefault, { Home } from './icon/Home.ts';
import HourglassDefault, { Hourglass } from './icon/Hourglass.ts';
import Html5Default, { Html5 } from './icon/Html5.ts';
import IdcardDefault, { Idcard } from './icon/Idcard.ts';
import IeCircleDefault, { IeCircle } from './icon/IeCircle.ts';
import IeSquareDefault, { IeSquare } from './icon/IeSquare.ts';
import InfoCircleDefault, { InfoCircle } from './icon/InfoCircle.ts';
import InstagramDefault, { Instagram } from './icon/Instagram.ts';
import InsuranceDefault, { Insurance } from './icon/Insurance.ts';
import InteractionDefault, { Interaction } from './icon/Interaction.ts';
import LayoutDefault, { Layout } from './icon/Layout.ts';
import LeftCircleDefault, { LeftCircle } from './icon/LeftCircle.ts';
import LeftSquareDefault, { LeftSquare } from './icon/LeftSquare.ts';
import LikeDefault, { Like } from './icon/Like.ts';
import LinkedinDefault, { Linkedin } from './icon/Linkedin.ts';
import LockDefault, { Lock } from './icon/Lock.ts';
import MacCommandDefault, { MacCommand } from './icon/MacCommand.ts';
import MailDefault, { Mail } from './icon/Mail.ts';
import MedicineBoxDefault, { MedicineBox } from './icon/MedicineBox.ts';
import MediumCircleDefault, { MediumCircle } from './icon/MediumCircle.ts';
import MediumSquareDefault, { MediumSquare } from './icon/MediumSquare.ts';
import MehDefault, { Meh } from './icon/Meh.ts';
import MessageDefault, { Message } from './icon/Message.ts';
import MinusCircleDefault, { MinusCircle } from './icon/MinusCircle.ts';
import MinusSquareDefault, { MinusSquare } from './icon/MinusSquare.ts';
import MobileDefault, { Mobile } from './icon/Mobile.ts';
import MoneyCollectDefault, { MoneyCollect } from './icon/MoneyCollect.ts';
import NotificationDefault, { Notification } from './icon/Notification.ts';
import PauseCircleDefault, { PauseCircle } from './icon/PauseCircle.ts';
import PayCircleDefault, { PayCircle } from './icon/PayCircle.ts';
import PhoneDefault, { Phone } from './icon/Phone.ts';
import PictureDefault, { Picture } from './icon/Picture.ts';
import PieChartDefault, { PieChart } from './icon/PieChart.ts';
import PlayCircleDefault, { PlayCircle } from './icon/PlayCircle.ts';
import PlaySquareDefault, { PlaySquare } from './icon/PlaySquare.ts';
import PlusCircleDefault, { PlusCircle } from './icon/PlusCircle.ts';
import PlusSquareDefault, { PlusSquare } from './icon/PlusSquare.ts';
import PoundCircleDefault, { PoundCircle } from './icon/PoundCircle.ts';
import PrinterDefault, { Printer } from './icon/Printer.ts';
import ProfileDefault, { Profile } from './icon/Profile.ts';
import ProjectDefault, { Project } from './icon/Project.ts';
import PropertySafetyDefault, { PropertySafety } from './icon/PropertySafety.ts';
import PushpinDefault, { Pushpin } from './icon/Pushpin.ts';
import QqCircleDefault, { QqCircle } from './icon/QqCircle.ts';
import QqSquareDefault, { QqSquare } from './icon/QqSquare.ts';
import QuestionCircleDefault, { QuestionCircle } from './icon/QuestionCircle.ts';
import ReadDefault, { Read } from './icon/Read.ts';
import ReconciliationDefault, { Reconciliation } from './icon/Reconciliation.ts';
import RedEnvelopeDefault, { RedEnvelope } from './icon/RedEnvelope.ts';
import RedditCircleDefault, { RedditCircle } from './icon/RedditCircle.ts';
import RedditSquareDefault, { RedditSquare } from './icon/RedditSquare.ts';
import RestDefault, { Rest } from './icon/Rest.ts';
import RightCircleDefault, { RightCircle } from './icon/RightCircle.ts';
import RightSquareDefault, { RightSquare } from './icon/RightSquare.ts';
import RobotDefault, { Robot } from './icon/Robot.ts';
import RocketDefault, { Rocket } from './icon/Rocket.ts';
import SafetyCertificateDefault, { SafetyCertificate } from './icon/SafetyCertificate.ts';
import SaveDefault, { Save } from './icon/Save.ts';
import ScheduleDefault, { Schedule } from './icon/Schedule.ts';
import SecurityScanDefault, { SecurityScan } from './icon/SecurityScan.ts';
import SettingDefault, { Setting } from './icon/Setting.ts';
import ShopDefault, { Shop } from './icon/Shop.ts';
import ShoppingDefault, { Shopping } from './icon/Shopping.ts';
import SignalDefault, { Signal } from './icon/Signal.ts';
import SketchCircleDefault, { SketchCircle } from './icon/SketchCircle.ts';
import SketchSquareDefault, { SketchSquare } from './icon/SketchSquare.ts';
import SkinDefault, { Skin } from './icon/Skin.ts';
import SkypeDefault, { Skype } from './icon/Skype.ts';
import SlackCircleDefault, { SlackCircle } from './icon/SlackCircle.ts';
import SlackSquareDefault, { SlackSquare } from './icon/SlackSquare.ts';
import SlidersDefault, { Sliders } from './icon/Sliders.ts';
import SmileDefault, { Smile } from './icon/Smile.ts';
import SnippetsDefault, { Snippets } from './icon/Snippets.ts';
import SoundDefault, { Sound } from './icon/Sound.ts';
import StarDefault, { Star } from './icon/Star.ts';
import StepBackwardDefault, { StepBackward } from './icon/StepBackward.ts';
import StepForwardDefault, { StepForward } from './icon/StepForward.ts';
import StopDefault, { Stop } from './icon/Stop.ts';
import SwitcherDefault, { Switcher } from './icon/Switcher.ts';
import TabletDefault, { Tablet } from './icon/Tablet.ts';
import TagDefault, { Tag } from './icon/Tag.ts';
import TagsDefault, { Tags } from './icon/Tags.ts';
import TaobaoCircleDefault, { TaobaoCircle } from './icon/TaobaoCircle.ts';
import TaobaoSquareDefault, { TaobaoSquare } from './icon/TaobaoSquare.ts';
import ThunderboltDefault, { Thunderbolt } from './icon/Thunderbolt.ts';
import ToolDefault, { Tool } from './icon/Tool.ts';
import TrademarkCircleDefault, { TrademarkCircle } from './icon/TrademarkCircle.ts';
import TrophyDefault, { Trophy } from './icon/Trophy.ts';
import TwitterCircleDefault, { TwitterCircle } from './icon/TwitterCircle.ts';
import TwitterSquareDefault, { TwitterSquare } from './icon/TwitterSquare.ts';
import UnlockDefault, { Unlock } from './icon/Unlock.ts';
import UpCircleDefault, { UpCircle } from './icon/UpCircle.ts';
import UpSquareDefault, { UpSquare } from './icon/UpSquare.ts';
import UsbDefault, { Usb } from './icon/Usb.ts';
import VideoCameraDefault, { VideoCamera } from './icon/VideoCamera.ts';
import WalletDefault, { Wallet } from './icon/Wallet.ts';
import WarningDefault, { Warning } from './icon/Warning.ts';
import WechatDefault, { Wechat } from './icon/Wechat.ts';
import WeiboCircleDefault, { WeiboCircle } from './icon/WeiboCircle.ts';
import WeiboSquareDefault, { WeiboSquare } from './icon/WeiboSquare.ts';
import WindowsDefault, { Windows } from './icon/Windows.ts';
import YahooDefault, { Yahoo } from './icon/Yahoo.ts';
import YoutubeDefault, { Youtube } from './icon/Youtube.ts';
import YuqueDefault, { Yuque } from './icon/Yuque.ts';
import ZhihuCircleDefault, { ZhihuCircle } from './icon/ZhihuCircle.ts';
import ZhihuSquareDefault, { ZhihuSquare } from './icon/ZhihuSquare.ts';


export { SvgBase, IconBase }
export { AccountBook };
export { Alert };
export { AlipayCircle };
export { AlipaySquare };
export { Aliwangwang };
export { AmazonCircle };
export { AmazonSquare };
export { Android };
export { Api };
export { Apple };
export { Appstore };
export { Audio };
export { Backward };
export { Bank };
export { BehanceCircle };
export { BehanceSquare };
export { Bell };
export { Book };
export { BoxPlot };
export { Bug };
export { Build };
export { Bulb };
export { Calculator };
export { Calendar };
export { Camera };
export { Car };
export { CaretDown };
export { CaretLeft };
export { CaretRight };
export { CaretUp };
export { CarryOut };
export { CheckCircle };
export { CheckSquare };
export { Chrome };
export { CiCircle };
export { ClockCircle };
export { CloseCircle };
export { CloseSquare };
export { Cloud };
export { CodeSandboxCircle };
export { CodeSandboxSquare };
export { Code };
export { CodepenCircle };
export { CodepenSquare };
export { Compass };
export { Contacts };
export { Container };
export { Control };
export { Copy };
export { CopyrightCircle };
export { CreditCard };
export { Crown };
export { CustomerService };
export { Dashboard };
export { Database };
export { Delete };
export { Diff };
export { DingtalkCircle };
export { DingtalkSquare };
export { Dislike };
export { DollarCircle };
export { DownCircle };
export { DownSquare };
export { DribbbleCircle };
export { DribbbleSquare };
export { DropboxCircle };
export { DropboxSquare };
export { Edit };
export { Environment };
export { EuroCircle };
export { ExclamationCircle };
export { Experiment };
export { EyeInvisible };
export { Eye };
export { Facebook };
export { FastBackward };
export { FastForward };
export { FileAdd };
export { FileExcel };
export { FileExclamation };
export { FileImage };
export { FileMarkdown };
export { FilePdf };
export { FilePpt };
export { FileText };
export { FileUnknown };
export { FileWord };
export { FileZip };
export { File };
export { Filter };
export { Fire };
export { Flag };
export { FolderAdd };
export { FolderOpen };
export { Folder };
export { FormatPainter };
export { Forward };
export { Frown };
export { Fund };
export { FunnelPlot };
export { Gift };
export { Github };
export { Gitlab };
export { Gold };
export { Golden };
export { GoogleCircle };
export { GooglePlusCircle };
export { GooglePlusSquare };
export { GoogleSquare };
export { Hdd };
export { Heart };
export { Highlight };
export { Home };
export { Hourglass };
export { Html5 };
export { Idcard };
export { IeCircle };
export { IeSquare };
export { InfoCircle };
export { Instagram };
export { Insurance };
export { Interaction };
export { Layout };
export { LeftCircle };
export { LeftSquare };
export { Like };
export { Linkedin };
export { Lock };
export { MacCommand };
export { Mail };
export { MedicineBox };
export { MediumCircle };
export { MediumSquare };
export { Meh };
export { Message };
export { MinusCircle };
export { MinusSquare };
export { Mobile };
export { MoneyCollect };
export { Notification };
export { PauseCircle };
export { PayCircle };
export { Phone };
export { Picture };
export { PieChart };
export { PlayCircle };
export { PlaySquare };
export { PlusCircle };
export { PlusSquare };
export { PoundCircle };
export { Printer };
export { Profile };
export { Project };
export { PropertySafety };
export { Pushpin };
export { QqCircle };
export { QqSquare };
export { QuestionCircle };
export { Read };
export { Reconciliation };
export { RedEnvelope };
export { RedditCircle };
export { RedditSquare };
export { Rest };
export { RightCircle };
export { RightSquare };
export { Robot };
export { Rocket };
export { SafetyCertificate };
export { Save };
export { Schedule };
export { SecurityScan };
export { Setting };
export { Shop };
export { Shopping };
export { Signal };
export { SketchCircle };
export { SketchSquare };
export { Skin };
export { Skype };
export { SlackCircle };
export { SlackSquare };
export { Sliders };
export { Smile };
export { Snippets };
export { Sound };
export { Star };
export { StepBackward };
export { StepForward };
export { Stop };
export { Switcher };
export { Tablet };
export { Tag };
export { Tags };
export { TaobaoCircle };
export { TaobaoSquare };
export { Thunderbolt };
export { Tool };
export { TrademarkCircle };
export { Trophy };
export { TwitterCircle };
export { TwitterSquare };
export { Unlock };
export { UpCircle };
export { UpSquare };
export { Usb };
export { VideoCamera };
export { Wallet };
export { Warning };
export { Wechat };
export { WeiboCircle };
export { WeiboSquare };
export { Windows };
export { Yahoo };
export { Youtube };
export { Yuque };
export { ZhihuCircle };
export { ZhihuSquare };


export default {
  install(app) {
    app.use(AccountBookDefault);
app.use(AlertDefault);
app.use(AlipayCircleDefault);
app.use(AlipaySquareDefault);
app.use(AliwangwangDefault);
app.use(AmazonCircleDefault);
app.use(AmazonSquareDefault);
app.use(AndroidDefault);
app.use(ApiDefault);
app.use(AppleDefault);
app.use(AppstoreDefault);
app.use(AudioDefault);
app.use(BackwardDefault);
app.use(BankDefault);
app.use(BehanceCircleDefault);
app.use(BehanceSquareDefault);
app.use(BellDefault);
app.use(BookDefault);
app.use(BoxPlotDefault);
app.use(BugDefault);
app.use(BuildDefault);
app.use(BulbDefault);
app.use(CalculatorDefault);
app.use(CalendarDefault);
app.use(CameraDefault);
app.use(CarDefault);
app.use(CaretDownDefault);
app.use(CaretLeftDefault);
app.use(CaretRightDefault);
app.use(CaretUpDefault);
app.use(CarryOutDefault);
app.use(CheckCircleDefault);
app.use(CheckSquareDefault);
app.use(ChromeDefault);
app.use(CiCircleDefault);
app.use(ClockCircleDefault);
app.use(CloseCircleDefault);
app.use(CloseSquareDefault);
app.use(CloudDefault);
app.use(CodeSandboxCircleDefault);
app.use(CodeSandboxSquareDefault);
app.use(CodeDefault);
app.use(CodepenCircleDefault);
app.use(CodepenSquareDefault);
app.use(CompassDefault);
app.use(ContactsDefault);
app.use(ContainerDefault);
app.use(ControlDefault);
app.use(CopyDefault);
app.use(CopyrightCircleDefault);
app.use(CreditCardDefault);
app.use(CrownDefault);
app.use(CustomerServiceDefault);
app.use(DashboardDefault);
app.use(DatabaseDefault);
app.use(DeleteDefault);
app.use(DiffDefault);
app.use(DingtalkCircleDefault);
app.use(DingtalkSquareDefault);
app.use(DislikeDefault);
app.use(DollarCircleDefault);
app.use(DownCircleDefault);
app.use(DownSquareDefault);
app.use(DribbbleCircleDefault);
app.use(DribbbleSquareDefault);
app.use(DropboxCircleDefault);
app.use(DropboxSquareDefault);
app.use(EditDefault);
app.use(EnvironmentDefault);
app.use(EuroCircleDefault);
app.use(ExclamationCircleDefault);
app.use(ExperimentDefault);
app.use(EyeInvisibleDefault);
app.use(EyeDefault);
app.use(FacebookDefault);
app.use(FastBackwardDefault);
app.use(FastForwardDefault);
app.use(FileAddDefault);
app.use(FileExcelDefault);
app.use(FileExclamationDefault);
app.use(FileImageDefault);
app.use(FileMarkdownDefault);
app.use(FilePdfDefault);
app.use(FilePptDefault);
app.use(FileTextDefault);
app.use(FileUnknownDefault);
app.use(FileWordDefault);
app.use(FileZipDefault);
app.use(FileDefault);
app.use(FilterDefault);
app.use(FireDefault);
app.use(FlagDefault);
app.use(FolderAddDefault);
app.use(FolderOpenDefault);
app.use(FolderDefault);
app.use(FormatPainterDefault);
app.use(ForwardDefault);
app.use(FrownDefault);
app.use(FundDefault);
app.use(FunnelPlotDefault);
app.use(GiftDefault);
app.use(GithubDefault);
app.use(GitlabDefault);
app.use(GoldDefault);
app.use(GoldenDefault);
app.use(GoogleCircleDefault);
app.use(GooglePlusCircleDefault);
app.use(GooglePlusSquareDefault);
app.use(GoogleSquareDefault);
app.use(HddDefault);
app.use(HeartDefault);
app.use(HighlightDefault);
app.use(HomeDefault);
app.use(HourglassDefault);
app.use(Html5Default);
app.use(IdcardDefault);
app.use(IeCircleDefault);
app.use(IeSquareDefault);
app.use(InfoCircleDefault);
app.use(InstagramDefault);
app.use(InsuranceDefault);
app.use(InteractionDefault);
app.use(LayoutDefault);
app.use(LeftCircleDefault);
app.use(LeftSquareDefault);
app.use(LikeDefault);
app.use(LinkedinDefault);
app.use(LockDefault);
app.use(MacCommandDefault);
app.use(MailDefault);
app.use(MedicineBoxDefault);
app.use(MediumCircleDefault);
app.use(MediumSquareDefault);
app.use(MehDefault);
app.use(MessageDefault);
app.use(MinusCircleDefault);
app.use(MinusSquareDefault);
app.use(MobileDefault);
app.use(MoneyCollectDefault);
app.use(NotificationDefault);
app.use(PauseCircleDefault);
app.use(PayCircleDefault);
app.use(PhoneDefault);
app.use(PictureDefault);
app.use(PieChartDefault);
app.use(PlayCircleDefault);
app.use(PlaySquareDefault);
app.use(PlusCircleDefault);
app.use(PlusSquareDefault);
app.use(PoundCircleDefault);
app.use(PrinterDefault);
app.use(ProfileDefault);
app.use(ProjectDefault);
app.use(PropertySafetyDefault);
app.use(PushpinDefault);
app.use(QqCircleDefault);
app.use(QqSquareDefault);
app.use(QuestionCircleDefault);
app.use(ReadDefault);
app.use(ReconciliationDefault);
app.use(RedEnvelopeDefault);
app.use(RedditCircleDefault);
app.use(RedditSquareDefault);
app.use(RestDefault);
app.use(RightCircleDefault);
app.use(RightSquareDefault);
app.use(RobotDefault);
app.use(RocketDefault);
app.use(SafetyCertificateDefault);
app.use(SaveDefault);
app.use(ScheduleDefault);
app.use(SecurityScanDefault);
app.use(SettingDefault);
app.use(ShopDefault);
app.use(ShoppingDefault);
app.use(SignalDefault);
app.use(SketchCircleDefault);
app.use(SketchSquareDefault);
app.use(SkinDefault);
app.use(SkypeDefault);
app.use(SlackCircleDefault);
app.use(SlackSquareDefault);
app.use(SlidersDefault);
app.use(SmileDefault);
app.use(SnippetsDefault);
app.use(SoundDefault);
app.use(StarDefault);
app.use(StepBackwardDefault);
app.use(StepForwardDefault);
app.use(StopDefault);
app.use(SwitcherDefault);
app.use(TabletDefault);
app.use(TagDefault);
app.use(TagsDefault);
app.use(TaobaoCircleDefault);
app.use(TaobaoSquareDefault);
app.use(ThunderboltDefault);
app.use(ToolDefault);
app.use(TrademarkCircleDefault);
app.use(TrophyDefault);
app.use(TwitterCircleDefault);
app.use(TwitterSquareDefault);
app.use(UnlockDefault);
app.use(UpCircleDefault);
app.use(UpSquareDefault);
app.use(UsbDefault);
app.use(VideoCameraDefault);
app.use(WalletDefault);
app.use(WarningDefault);
app.use(WechatDefault);
app.use(WeiboCircleDefault);
app.use(WeiboSquareDefault);
app.use(WindowsDefault);
app.use(YahooDefault);
app.use(YoutubeDefault);
app.use(YuqueDefault);
app.use(ZhihuCircleDefault);
app.use(ZhihuSquareDefault);

  }
}

